version: '3.8'
name: metis-bot-services

services:

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

      
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - 8081:8081
    depends_on:
      - db

  app:
    build: .  # Path where your Dockerfile is located
    container_name: bot-t-agent
    restart: always
    env_file: .env
    depends_on:
      - db
    command: python run.py
    ports:
      - 8000:8000
    volumes:
      - .:/app
    links:
      - db



  