# version: '3.5'

services:
  app:
    platform: linux/amd64
    container_name: siai_t_bot
    restart: always
    build: .
    ports:
      - "8000:8000"
    # command: sh -c "sleep 10s ; python3 ./app.py"
    entrypoint: ["./entrypoint.sh"]
   



  